<?php

namespace AppBundle\Repository;

/**
 * GroupeVideosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeVideosRepository extends \Doctrine\ORM\EntityRepository
{
}
