<?php

namespace AppBundle\Repository;

/**
 * ParcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcoursRepository extends \Doctrine\ORM\EntityRepository
{
}
