yk_competences_add:
    path:     /competences/add
    defaults: { _controller: YKCompetencesBundle:Competences:add }

yk_competences_show_all:
    path:     /competences/all
    defaults: { _controller: YKCompetencesBundle:Competences:showAll }

yk_competences_show:
    path:     /competences/{id}
    defaults: { _controller: YKCompetencesBundle:Competences:show }
