yk_competences_homepage:
    path:     /
    defaults: { _controller: YKCompetencesBundle:Default:index }

yk_competences_add:
    path:     /add
    defaults: { _controller: YKCompetencesBundle:Default:add }
    
yk_competences_show_all:
    path:     /competences
    defaults: { _controller: YKCompetencesBundle:Default:showAll }

yk_competences_show:
    path:     /competences/{id}
    defaults: { _controller: YKCompetencesBundle:Default:show }
