yk_projets_add:
    path:     /projets/add
    defaults: { _controller: YKProjetsBundle:Projets:add }

yk_projets_show_all:
    path:     /projets/all
    defaults: { _controller: YKProjetsBundle:Projets:showAll }

yk_projets_show:
    path:     /projets/{id}
    defaults: { _controller: YKProjetsBundle:Projets:show }
