yk_projets_homepage:
    path:     /
    defaults: { _controller: YKProjetsBundle:Default:index }
yk_projets_add:
    path:     /projets/add
    defaults: { _controller: YKProjetsBundle:Default:add }
    
yk_projets_show_all:
    path:     /projets
    defaults: { _controller: YKProjetsBundle:Default:showAll }

yk_projets_show:
    path:     /projets/{id}
    defaults: { _controller: YKProjetsBundle:Default:show }
