yk_users_contact:
    path:     /contact
    defaults: { _controller: YKUsersBundle:Users:contact }

yk_users_index:
    path:     /index
    defaults: { _controller: YKUsersBundle:Users:index }

yk_users_scan:
    path:     /scan/{index}
    defaults: { _controller: YKUsersBundle:Scan:download }
