yk_video_show_all:
    path:     /video/all
    defaults: { _controller: YKVideoBundle:Video:showAll }

yk_video_show:
    path:     /video/{id}
    defaults: { _controller: YKVideoBundle:Video:show }

yk_groupesVideos_add:
    path:     /videos/add
    defaults: { _controller: YKVideoBundle:GroupeVideos:add }

yk_groupesVideos_addVideo:
    path:     /video/{id}/add
    defaults: { _controller: YKVideoBundle:GroupeVideos:addVideo }

yk_groupesVideos_show_all:
    path:     /videos/all
    defaults: { _controller: YKVideoBundle:GroupeVideos:showAll }

yk_groupesVideos_show:
    path:     /videos/{id}
    defaults: { _controller: YKVideoBundle:GroupeVideos:show }
